name = "rematch-web-app-v2"
compatibility_date = "2024-05-05"
compatibility_flags = ["nodejs_compat"]

# For Next.js Sites
[build]
command = "npm run build"

[site]
bucket = ".next/static"

[build.upload]
format = "service-worker"

# Assets configuration
[assets]
directory = ".next/static"

